[theme]
primaryColor = "#d33682"  # The color used for buttons and other primary UI elements
backgroundColor = "#002b36"  # Background color of the app
secondaryBackgroundColor = "#586e75"  # Background color for sidebar or secondary elements
textColor = "#ffffff"  # Text color (white for dark mode)
font = "sans serif"  # Font used in the app
